name: Store Api CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      MONGO_URL : ${{ secrets.MONGO_URL }}
      PORT : ${{ secrets.PORT }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_EXPIRE_IN: ${{ secrets.JWT_EXPIRE_IN }}
      SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_FOLDER: ${{ secrets.CLOUDINARY_FOLDER }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      STRIPE_FRONTEND_KEY: ${{ secrets.STRIPE_FRONTEND_KEY }}
      STRIPE_BACKEND_KEY: ${{ secrets.STRIPE_BACKEND_KEY }}
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
        mongodb-version: ["5.0"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use MongoDB Action
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install

      - name: Run tests
        run: npm test
